#!/bin/sh

export NODE_ENV=production

now=$(date +"%T")

. ./bash/colors

stop() {
	echo "${CLR_RED}Stopping Redis-Server and PM2...${CLR_NORMAL}"
	redis-cli -p 6969 shutdown > /dev/null
	pm2 stop all
	echo "${CLR_RED}Stopped.${CLR_NORMAL}"
}

start() {
	echo "${CLR_YELLOW}Starting Redis-Server (port 6969) and PM2 (app.js)${CLR_NORMAL}"
	redis-server redis.conf --port 6969 > /dev/null
	pm2 start app.js
	echo "${CLR_YELLOW}Started.${CLR_NORMAL}"
	
	# > /dev/null
}

# Here's the switch statement:
case $1 in
	"restart")
		stop
		start ;;
	"stop") stop ;;
	"start") start ;;
	"push")
		echo "Pulling first..."
                git pull
		echo "Adding, Committing and Pushing to origin 'master'..."
		git add -A
		git commit -m "Pushed from server at $now"
		git push origin
		echo "${CLR_YELLOW}Pushed all server changes to Master.${CLR_NORMAL}"
		;;
	"pull")
		stop
		git pull > /dev/null
		yarn > /dev/null
		start ;;
	*)
		stop
		start ;;
esac
