#!/bin/sh

export NODE_ENV=production

now=$(date +"%T")

. ./bash/colors

stop() {
	echo "${CLR_RED}Stopping Redis-Server and Forever...${CLR_NORMAL}"
	redis-cli -p 6969 shutdown > /dev/null
	forever stopall > /dev/null
	echo "${CLR_RED}Stopped.${CLR_NORMAL}"
}

start() {
	echo "${CLR_YELLOW}Starting Redis-Server (port 6969) and Forever (app.js)${CLR_NORMAL}"
	redis-server redis.conf --port 6969 > /dev/null
	forever start app.js > /dev/null
	echo "${CLR_YELLOW}Started.${CLR_NORMAL}"
}

case $1 in
	"restart")
		stop
		start ;;
	"stop") stop ;;
	"start") start ;;
	"push")
		git pull
		git add -A
		git commit -m "Pushed from server at $now"
		git push
		stop
		start ;;
	"pull")
		git pull
		stop
		start ;;
	*)
		stop
		start ;;
esac